/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package wordjourney.graphics.components;

/**
 *
 * @author alexalmanza
 */
public class TestWordle extends javax.swing.JPanel {

    /**
     * Creates new form TestWordle
     */
    public TestWordle() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JTextField jTextField1 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField2 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField3 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField4 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField5 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField6 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField7 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField8 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField9 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField10 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField11 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField12 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField13 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField14 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField15 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField16 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField17 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField18 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField19 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField20 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField21 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField22 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField23 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField24 = new javax.swing.JTextField();
        javax.swing.JTextField jTextField25 = new javax.swing.JTextField();

        setMaximumSize(new java.awt.Dimension(200, 200));
        setMinimumSize(new java.awt.Dimension(200, 200));
        setLayout(new java.awt.GridLayout(5, 5));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        add(jTextField1);
        add(jTextField2);
        add(jTextField3);
        add(jTextField4);
        add(jTextField5);
        add(jTextField6);
        add(jTextField7);
        add(jTextField8);
        add(jTextField9);
        add(jTextField10);
        add(jTextField11);
        add(jTextField12);
        add(jTextField13);
        add(jTextField14);
        add(jTextField15);
        add(jTextField16);
        add(jTextField17);
        add(jTextField18);
        add(jTextField19);
        add(jTextField20);
        add(jTextField21);
        add(jTextField22);
        add(jTextField23);
        add(jTextField24);
        add(jTextField25);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
